### PR TITLE
Added support for Astronomy

### PR DESCRIPTION
**Pull request by RSchwan**
See #44 
This is my current progress. First level fields should work, but nested fields and arrays aren't working.

### CODE REVIEW

**Comment by radekmie** [comment]
Great work! Could you tell something more about those _not working_ fields? Maybe I'll try to finish it.

**Comment by RSchwan** [comment]
Basically there is no method like `getDefinition`. `schema.getField` only works for the first level. So  recursion is probably the way to go. It's all pretty hacky. I looked up the available methods and attributes of the schema with the dev tools (create a test schema and `console.log` it).
I hope this helps.

**Comment by radekmie** [comment]
Yes, that's helpful. I'll try to take a deeper look at it. Thanks anyway!

**Comment by fawzisf** [comment]
Any updates on this PR ?
I'm currently using uniforms in all my projects, and i might start using astronomy, so maybe i can continue the help here ?

**Comment by radekmie** [comment]
Hi @fawzisf. Well, not really, as you can see. Of course, you can continue this PR or create a new one. I'm still not using Astronomy, but I can help you on the uniforms side.

**Comment by radekmie** [comment]
It's a very old pull request. I'm closing due to inactivity, but feel free to pick it up and continue.

**Pull request closed without merging**
