### PR TITLE
Migrated from Jest to Vitest.

### PR DESCRIPTION
**Pull request by radekmie**
As discussed, I propose a migration from Jest to Vitest. The configuration and tests themselves are basically the same, but I saw a performance improvement (~5-10%) as well as better stability of the watch mode. It also comes with a few nice features, i.e., [`assertType`](https://vitest.dev/api/assert-type.html) or [`bench`](https://vitest.dev/api/#bench)marking. I've also tried switching to [`happy-dom`](https://vitest.dev/config/#environment) but failed miserably.

**EDIT:** This drop in coverage is a result of more accurate measurements - now it's coverage of the `imports`-based code, not the `require`-based one. See the screenshots for comparison. (It's still based on `istanbul`; I've tried `c8` but it missed _a lot_ of code.)

| `jest` | `vitest` |
|:-:|:-:|
|image|image|

### CODE REVIEW

**Review by kestarumper — APPROVED** [review]

**Review by Monteth — APPROVED** [review]
Jest is still faster on my PC 🤔

**Comment by radekmie** [comment]
@Monteth Do you have the times at hand?

**Comment by Monteth** [comment]
@radekmie I run `npm ci` and then `npm run test` on the current `master` branch with 41.1s and on `vitest` with 41.8 on node v16.19.0.

**Comment by radekmie** [comment]
Now it's also slower on my end:
```
 Test Files  210 passed (210)
      Tests  2828 passed | 5 skipped (2833)
   Start at  14:28:15
   Duration  30.31s (transform 1.92s, setup 37.77s, collect 45.05s, tests 29.47s)

CI=1 npx vitest  185.61s user 23.03s system 678% cpu 30.758 total
```
```
Test Suites: 210 passed, 210 total
Tests:       5 skipped, 2828 passed, 2833 total
Snapshots:   0 total
Time:        22.431 s
Ran all test suites.
CI=1 npx jest  144.48s user 13.35s system 667% cpu 23.647 total
```

That's weird 😕

**Comment by Monteth** [comment]
A quick check on the CI runs also shows degraded performance on this branch

**Pull request closed without merging**
