### PR TITLE
Implemented custom AutoField prototype.

### LINKED ISSUE #640: make it more easy to replace components without requiring to implement a custom AutoField
If you just want to replace one field (e.g. replace the ListField with a custom one for all schemas), you need to reimplement the whole AutoField.

It would probably easier, if you could pass a `getFieldComponent` to a AutoForm, which would hook into here: https://github.com/vazco/uniforms/blob/master/packages/uniforms-material/src/AutoField.tsx#L24 and would take `props` and could return a Component. If no component is returned, it would fallback to the normal logic.

### PR DESCRIPTION
**Pull request by radekmie**
This change provides a new implementation of `AutoField` and an according `AutoFieldContext` to override field detection implementation. Internally a `createAutoField` was added as well in order to reduce the amount of boilerplate theme code to a minimum.

Open questions:
* Is `AutoFieldContext` a good name? Maybe `AutoField.context` or `AutoField.componentDetectorContext` is a better one?
* What about `createAutoField` - should we consider it an internal API for now/forever?
* Right now overriding the default detector requires always return a component. In order to fall back to the default one, one would have to either fetch the default one with `useContext` or implement it in their own project. Another solution would be to treat the provided one with a higher priority and fallback to the default one.

Closes #640.

---

Update 2020-12-21:
* I've decided to move `AutoFieldContext` to `AutoField.componentDetectorContext` in order to reduce API surface. We may change it in the future.
* All `createAutoField`, `AutoField.componentDetectorContext`, and `AutoField.defaultComponentDetector` are considered internal for now.
* Default detector is now accessible through `AutoField.defaultComponentDetector`.

### CODE REVIEW

**Comment by Monteth** [comment]
1.)  `AutoFieldContext` seems like good name for that. 
2.) I don't see why someone would use that, maybe we shouldn't introduce a flood of API that no one will use.
3.) I would say many users may want to replace only one/very few components and they won't write the whole detector as most of its job is still correct.

**Comment by kestarumper** [comment]
1. After some thought, `AutoFieldContext` seems to be the right choice. Imagine writing `AutoField.context.Provider` - it looks strange.
2. I actually like `createAutoField` helper. It reduces boilerplate code and makes sure that we use `connectField(..., { kind: 'leaf' })` for performance reasons. Most of the time, overriding `AutoField` (by writing it yourself) leads to reinventing the wheel. With the use of `createAutoField`, I can focus on **selecting the right component**  based on its props - and that's all that I need.
3. I don't know if that's overkill, but we could `export` `defaultComponentDetector` which accepts a `map` of components
```javascript
{
    BoolField: MyCustomBoolField,
...
}
```
Then if someone would only want to override (or create a new theme), one would pass overridden map and wouldn't have to change the `switch` logic.

If component return logic is more complicated than based on the default, one could write its own `componentDetector` and if needed use and fallback to our exported `defaultComponentDetector`.

**Review by kestarumper — DISMISSED** [review]

**Comment by radekmie** [comment]
@kestarumper 
1. I can imagine `AutoField.context.Provider`. And I think it's actually better than a new export from the theme.
2. No, `createAutoField` won't add `kind: 'leaf'` for you - it'll only use it when it's there.
3. The `defaultComponentDetector` would have to be a function already ([see the `allowedValues` branch](https://github.com/vazco/uniforms/blob/7c9f23a8b1d66a415d78aa1203bb1dd5591a38e7/packages/uniforms-unstyled/src/AutoField.tsx#L16-L20)). There's no need for it anyway, if we'd go with _default if `undefined`_.

**Comment by kestarumper** [comment]
> No, createAutoField won't add kind: 'leaf' for you - it'll only use it when it's there.

I meant only that if you have your own implementation of `AutoField`, then if you don't do the following:
```javascript
return 'options' in component && component.options?.kind === 'leaf'
      ? createElement(component.Component, props)
      : createElement(component, originalProps);
```
then It's lost.

**Comment by radekmie** [comment]
I've updated the description. If everything will be fine, I'll update all themes.

**Review by Monteth — DISMISSED** [review]

**Review by kestarumper — DISMISSED** [review]

**Review by Monteth — DISMISSED** [review]

**Review by Monteth — APPROVED** [review]

**Pull request merged**
