### PR TITLE
Compatibility with StrictMode

### PR DESCRIPTION
**Pull request by piotrpospiech**
This fixes https://github.com/vazco/uniforms/issues/1194.

Overriding `setState` caused this issue. I removed it and added checking if the component is mounted before calling `setState`.

Tested with Vite, React `v18.2.0` and Strict Mode.

### CODE REVIEW

**Review by kestarumper — APPROVED** [review]
Have you tested it somehow?

**Review by zendranm — APPROVED** [review]

**Comment by mdesousa** [comment]
hi @piotrpospiech @zendranm thanks for this fix! wondering if there are plans to patch it in version 3?

**Comment by piotrpospiech** [comment]
Hi @mdesousa, we didn't consider it. Our focus is on version 4, which is nearly finished ([v4.0 Milestone](https://github.com/vazco/uniforms/milestone/8)) and mainly needs documentation updates. We don't plan more changes to v3 packages. If this fix is important for you, I'd recommend trying the v4 beta or waiting for the full v4 release coming soon.

**Comment by mdesousa** [comment]
Unfortunately our app is in production and can't upgrade to a beta library yet. We'd also expect that there will be breaking changes and more testing necessary to upgrade to 4.0... which we'll happily do when it's ready. But in the meantime getting this small patch for version 3 would help us with this issue that is impacting our production app. Thanks!

**Pull request merged**
