### PR TITLE
Add support for label classes

### PR DESCRIPTION
**Pull request by bigchirv**
For being able to alter the looks of the label without depending on 'grid'.

### CODE REVIEW

**Comment by radekmie** [comment]
Hi @bigchirv. Really small change looks good (docs!). Can you add it to the bootstrap3 theme too? A simple test would also be great.

**Comment by bigchirv** [comment]
Thanks for pointing out writing the tests, really forgot about them. :smiley:

On what file should I add the documentation on the labelClassName prop for bootstrap 3/4?

**Comment by radekmie** [comment]
It should be in [`docs/api-fields.md`](https://github.com/vazco/uniforms/blob/master/docs/api-fields.md).

**Comment by bigchirv** [comment]
Okay, I added the entries in `api-fields.md` as suggested.

**Comment by radekmie** [comment]
Thank you @bigchirv!

**Pull request merged**
