### PR TITLE
Update compare-matrix with react-hook-form

### PR DESCRIPTION
**Pull request by LeongXianJun**
The followings are the links that related to the feature mentioned
- synchronous validation: https://react-hook-form.com/api/#handleSubmit
- asynchronous validation: https://react-hook-form.com/api/#handleSubmit, https://codesandbox.io/s/xrjv48o0qp
- Field level validation: https://react-hook-form.com/advanced-usage#AccessibilityA11y, https://codesandbox.io/s/m5pj55yj7x
- Manual state management mode: https://react-hook-form.com/api/#setValue
- Manually trigger change: https://react-hook-form.com/api/#setValue
- Manually trigger reset: https://react-hook-form.com/api/#reset
- Manually trigger validation: https://react-hook-form.com/api/#trigger
- Built in focus state management: https://react-hook-form.com/api/#Controller

### CODE REVIEW

**Comment by radekmie** [comment]
Hi @LeongXianJun and thank you! I'll read through it later. For now, I see that the lint failed - use below script to let Prettier re-format it:
```sh
npx prettier --write docs/compare-matrix.md
```

**Comment by LeongXianJun** [comment]
@radekmie I had run the command accordingly but now it is not allowed me to commit the changes. It says that the file still has code style issues.

**Comment by radekmie** [comment]
@LeongXianJun Sanity check: have you `git add`ed it? If so, could you paste the error here?

**Comment by LeongXianJun** [comment]
@radekmie This is the screenshot when I made the commit
image

This is the status of git.
image

**Comment by LeongXianJun** [comment]
@radekmie Should I add --no-verify option when i commit?

**Comment by radekmie** [comment]
@LeongXianJun Try this:

```sh
npx prettier --write docs/compare-matrix.md
git add .
git commit -m 'Your message here...'
```

**Comment by LeongXianJun** [comment]
@radekmie Still cannot. Is it because of my nodejs is too old (v10.15.3) which make the husky fail to run pre-commit?

**Comment by radekmie** [comment]
@LeongXianJun no, Husky works - otherwise you wouldn't see this error. OK, try to commit with this ignore flag and we'll see if the CI works.

**Comment by LeongXianJun** [comment]
@radekmie Now the Lint Test passed. So, it might be my machine issue.

**Comment by LeongXianJun** [comment]
BTW, I think I need to update compare-matrix-landing.md as well. Just noticed we have this file.

**Comment by radekmie** [comment]
Thank you once more, @LeongXianJun!

**Pull request merged**
