### PR TITLE
reset sets model back to initial model

### PR DESCRIPTION
**Pull request by macrozone**
fixes https://github.com/vazco/uniforms/issues/140

however, something is odd:

In the demo, the form already contains default-values. not from the mode, but from the bridge/schema.

reset does not seem to restore these default-values and i am unsure whether this should be the case.

### CODE REVIEW

**Comment by radekmie** [comment]
Let me guess - you haven't noticed [this](https://github.com/vazco/uniforms/blob/master/demo/components/Application.js#L16)?

**Comment by radekmie** [comment]
Also, which form in the docs? The main one and the one on the left are managed.

**Comment by radekmie** [comment]
@macrozone

**Comment by macrozone** [comment]
@radekmie: the one on the right and yes, I haven't noticed that, but that cleans the schema for the form on the right.

The form on the right does not restore defaults, when you call reset, but it initially contains the default values. I would think that a reset should also restore defaults from the schema.

**Comment by radekmie** [comment]
@macrozone OK, now I understand. Look at [these lines](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/AutoForm.js#L63-L66). At first, we call [`BaseForm#reset`](https://github.com/vazco/uniforms/blob/master/packages/uniforms/src/components/forms/BaseForm.js#L243-L250), which will rerender the whole form, including calculation of default values. To fix it, we have to switch those lines in `AutoForm` or even call `super.onSubmit()` in the `setState` callback.

**Comment by radekmie** [comment]
@macrozone Will you test it, or should I do it by myself?

**Pull request merged**
