### PR TITLE
[WIP] Support material-ui v1

### PR DESCRIPTION
**Pull request by janowsiany**
#349 
Things which still need to be done:
- [x] layout
- [ ] tests
- [ ] ?icons

### CODE REVIEW

**Comment by radekmie** [comment]
We've decided internally, that this will be released along with `material-ui@1` and `uniforms-material` will be kept up to date with the newest release.

**Comment by tomscholz** [comment]
@janowsiany When using with `material-ui@1.0.0-beta.21` I get the following error:
```
Uncaught Error: Cannot find module 'material-ui/Toggle'
    at makeMissingError (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:231)
    at require (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:241)
    at BoolField.js (modules.js?hash=88f8f10435408c0f364ee2d499b1b0b3692ec77c:94333)
    at fileEvaluate (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343)
    at require (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238)
    at AutoField.js (modules.js?hash=88f8f10435408c0f364ee2d499b1b0b3692ec77c:94073)
    at fileEvaluate (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343)
    at require (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238)
    at AutoFields.js (modules.js?hash=88f8f10435408c0f364ee2d499b1b0b3692ec77c:90751)
    at fileEvaluate (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343)
```

Any ideas or thoughts how that could be solved?

**Comment by janowsiany** [comment]
Hey, @tomscholz sorry for this delay.
There were 5 `material-ui` beta realeased since i last checked this PR so perhaps they have made a breaking change. Could you confirm that with `1.0.0-beta.16` it is working?

**Comment by MkBeeCtrl** [comment]
@janowsiany Serwus, chciałem spytać o status, są jakieś szanse połączenia w najbliższej przyszłości?
Pewnie trudno wam nadążyć za ich beta branchem :/

Tak się akurat składa, że bardzo by mi się przydała ta część w moim projekcie. Można używać czy lepiej nie?

**Comment by janowsiany** [comment]
Hopefully `material-ui@1.0.0` [will be released on 17th of May](https://github.com/mui-org/material-ui/blob/v1-beta/CHANGELOG.md#100), so you may expect that `uniforms` will support the newly released version up to two weeks after the release date.

**Comment by raedle** [comment]
The @material-ui/core rc-0 is out. I'm happy to test a pre-release of uniforms/material-ui v1 :)

**Comment by janowsiany** [comment]
Closing in favor of #427

**Pull request closed without merging**
