### PR TITLE
Handled `min` and `max` props in Material UI and MUI (closes #1213).

### LINKED ISSUE #1213: [MUI] and [Material] `min` and `max` properties are not being applied to a Date field
The `min` and `max` properties are necessary to avoid that arbitrary values re entered in a `Date` type field, however, even setting 
```javascript
<AutoField
	type="date"
	variant="standard"
	min={<any value>}
	max={<any value>}
/>
```
they are not applied.

The code

image

generates the html

image

### PR DESCRIPTION
**Pull request by vcardins**
Following up on the issue https://github.com/vazco/uniforms/issues/1213#issuecomment-1416058859, this PR is suppose to fix it.

### CODE REVIEW

**Comment by radekmie** [comment]
Thanks for submitting it again! Two things:
1. It's missing [this code](https://github.com/vazco/uniforms/pull/1215#issuecomment-1440329406).
2. This PR should not touch anything else, like the Docusaurus version.

**Comment by vcardins** [comment]
Sorry for changing the package.json, I think I ran `npm audit --fix` and it caused it, reverted. Sorry, it's not clear which code is missing once the link takes me to the top of the file.

**Comment by radekmie** [comment]
The link I posted is the last comment of mine in the other PR (the one with the diff). And please revert the irrelevant changes, e.g., in `package.json`.

**Comment by vcardins** [comment]
I keep having issues, maybe versions related, could you try in your environment and help it to move forward?
Thanks

**Comment by radekmie** [comment]
OK, no problem. I'll push it to your fork. (Hopefully without breaking things this time.)

**Review by radekmie — APPROVED** [review]

**Review by kestarumper — APPROVED** [review]

**Review by radekmie — APPROVED** [review]

**Comment by vcardins** [comment]
@radekmie @kestarumper Thank you very much! Could you give an ETA of when the changes are going to published to `npm`?

**Comment by radekmie** [comment]
I plan to do a release on Friday.

**Comment by vcardins** [comment]
@radekmie Apologies for asking again, but any updates on this?

**Comment by radekmie** [comment]
4.0.0-alpha.2 got released a couple hours ago.

**Pull request merged**
