### PR TITLE
Section to div

### PR DESCRIPTION
**Pull request by zeroasterisk**
Switched from section --> div in ALL components

> Do not use the <section> element as a generic container; this is what <div> is for, especially when the sectioning is only for styling purposes. A rule of thumb is that a section should logically appear in the outline of a document.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

### CODE REVIEW

**Comment by radekmie** [comment]
OK, I will merge it after #170.

**Comment by radekmie** [comment]
@zeroasterisk, there are conflicts, due to #170 - I'll merge it after you'll solve them.

**Comment by radekmie** [comment]
@zeroasterisk will you have some time to do this?

**Comment by zeroasterisk** [comment]
Ok - I re-ran this `sed` after rebasing from master -- should be ok now.

**Pull request merged**
