### PR TITLE
Added html5 input types to text field

### PR DESCRIPTION
**Pull request by serkandurusoy**
@radekmie some input types were missing.

It would be best if we created proper inputs for them, but in the meantime, this quick override option should be able to serve most cases that don't need extra customization.

* did not add a test for this since there is only tests for the base field.
* tried to conform to the coding style of each component set.
* also did a quick update on the readme.
* incremented the version number to rc13

Let me know if this works for you.

### CODE REVIEW

**Comment by radekmie** [comment]
I'll merge it, but first:
* remove `checkInputType` - it's unnecessary (optionally use `propTypes` instead)
* reset version - lerna do it automatically, and it won't work if you update it by hand

**Comment by serkandurusoy** [comment]
Done!

What do you think?

**Comment by radekmie** [comment]
Great! One more question (because I can't do it right now) - are you passing `npm run lint`? If yes, I'll merge it in a minute.

**Comment by serkandurusoy** [comment]
hmm unfortunately the initial npm install hangs with lerna saying linking
all dependencies an it just freezes so I can't even try linting :(

Sent from my iPhone



On Jun 5, 2016, at 15:12, "Radosław Miernik" <notifications@github.com>
wrote:

Great! One more question (because I can't do it right now) - are you
passing npm run lint? If yes, I'll merge it in a minute.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vazco/uniforms/pull/19#issuecomment-223809838>, or mute
the thread
<https://github.com/notifications/unsubscribe/AEbz3JCZ0WqbBcnxIV2WzkUnIlMsOmP9ks5qIr1BgaJpZM4IuVUl>
.

**Comment by radekmie** [comment]
It's not frozen (probably) - it just takes a while. Also, you can `lint` and `test` every single package.

**Comment by serkandurusoy** [comment]
I get lots of very cryptic errors, seemingly unrelated to linting. I'll open an issue about "contribution guide"

**Comment by serkandurusoy** [comment]
Thanks for merging! When do you plan on pushing the release?

**Comment by radekmie** [comment]
Soon - I want to finish #17 first.

**Comment by serkandurusoy** [comment]
Cool! Thanks.

**Pull request merged**
