### PR TITLE
SemanticUI: Add support for input icons

### PR DESCRIPTION
**Pull request by MacRusher**
Adds ability to use icons in `TextField` component.

Example usage:
```javascript
<TextField name="username" icon="user" />
<TextField name="query" iconLeft="search" />
```
There could be only one icon, and `icon` take precedence before `iconLeft`.

I could also add support for [pointer events](http://semantic-ui.com/elements/input.html#icon) if you think it would useful:
```javascript
<TextField name="username" icon="add user" onIconClick={() => {}} />
```

One problem I'm aware of is that adding `ui icon input` classes change the input width.
This could be solved by adding `fluid` class either by `TextField` itself (IMHO bad idea) or end user:
```javascript
<TextField name="username" className="fluid" icon="user" />
```

### CODE REVIEW

**Comment by MacRusher** [comment]
Few changes.

Per @radekmie recommendation I've introduced new section for the input which may or may not contain icon classes. So the problem with different input sizes is gone now.

Instead of `onIconClick` etc. I've also introduced `icomProps` that are passed directly to `<i/>` element.
Example usage:
```javascript
<TextField name="username" icon="add user link" iconProps={{ onClick: () => {} }} />
```

**Comment by radekmie** [comment]
Great! Would you like to do the same for `DateField` and `NumField` also?

**Comment by MacRusher** [comment]
Sure, why not. I'll take care of this tomorrow.

**Comment by MacRusher** [comment]
I've added icon support for `DateField` and `NumField`

**Comment by radekmie** [comment]
Great!

**Pull request merged**
